### PR TITLE
yAudit reports first draft

### PR DESCRIPTION
**Pull request by engn33r**
Seeking feedback on whether this roughly follows the format of the other report parsers.

This is the first parser in the collection to parse markdown reports so I modified the parsing logic but tried to keep a similar structure and function names to the tob parser.

### CODE REVIEW

**Comment by joswha** [comment]
Looks good overall, we might have to change the formatting & structure of folders eventually, but for now it should be fine.

**Comment by joswha** [comment]
Feel free to incorporate the [yaudit_findings.json](https://github.com/Zellic/Masamune/pull/5/files#diff-3c4ca805b369c3c3726bb693b940ee83c2fbe5c28456c4c1156e059a170b0b65) in `logic.js` so that it's also searchable @engn33r

**Comment by engn33r** [comment]
Agree that folder structure could use some changes. I prefer separating each set of reports into a separate folder, either separated by audit firm or by parser, since it's possible a single audit firm may need more than 1 parser if they changed report formats at some point. It could make it easier to troubleshoot parser issues as this scales to support more reports.

A related comment, this repo will get large if all the original pdf reports are included into it. Even the existing PDFs are over 100Mb. Could we switch to submodules, so that we are pulling data directly from each public repository of reports?

**Comment by joswha** [comment]
Great idea with the submodules. I am currently working on a GPT powered version for Masamune. After that, will move on to refactoring and restructuring the code-base, but feel free to make any structural changes you see fit

**Pull request merged**
